SluaghEngine/Audio/Audio.vcxproj, SluaghEngine/Audio/Audio.vcxproj.filters, SluaghEngine/SluaghEngine.sln
I added the Audio Project(Module)
=> Added Audio project (module)

SluaghEngine/Input/Input.vcxproj, SluaghEngine/Input/Input.vcxproj.filters, SluaghEngine/SluaghEngine.sln
Added project for the input module.
=> Input Module

SluaghEngine/Audio/Audio.vcxproj
Changed the build target from .exe to .lib
=> Change exe to lib

SluaghEngine/Input/Input.vcxproj
Set up the project according to the CoC.
=> Updated project settings for Input module.

SluaghEngine/Graphics/Graphics.vcxproj, SluaghEngine/Input/Input.vcxproj
Updated Project Setting to follow updated CoC
=> Updated Project Setting

SluaghEngine/ResourceHandler/IAssetLoader.h, SluaghEngine/ResourceHandler/RawLoader.cpp, SluaghEngine/ResourceHandler/RawLoader.h, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.h, SluaghEngine/includes/ResourceHandler/IResourceHandler.h, SluaghEngine/includes/Utilz/PathParsing.h
Data is now returned in a callback function when calling the loadresource function
=> LoadResource data is returned

SluaghEngine/Test/WindowTest.cpp, SluaghEngine/Window/Input.cpp, SluaghEngine/includes/Window/KeyState.h
small changes mostly to KeyState.h
=> input is crap

SluaghEngine/Graphics/ConstantBufferHandler.cpp, SluaghEngine/Graphics/ConstantBufferHandler.h, SluaghEngine/Graphics/DeviceManager.cpp, SluaghEngine/Graphics/MaterialHandler.cpp, SluaghEngine/Graphics/StaticVertexBufferHandler.cpp, SluaghEngine/Graphics/StaticVertexBufferHandler.h, SluaghEngine/includes/Graphics/DeviceManager.h, SluaghEngine/includes/Graphics/MaterialHandler.h
I have removed all Com pointers from DeviceManager and MaterialHandler
=> Removal of Com Pointers

SluaghEngine/Gameplay/Flowfield.cpp, SluaghEngine/Gameplay/Flowfield.h, SluaghEngine/Gameplay/Gameplay.vcxproj, SluaghEngine/Gameplay/Gameplay.vcxproj.filters
Added the flowfield class and all it's basic funtions
=> Flowfield integration

SluaghEngine/Gameplay/EnemyUnit.cpp, SluaghEngine/Gameplay/Flowfield.cpp, SluaghEngine/Gameplay/GameUnit.cpp, SluaghEngine/Graphics/GraphicResourceHandler.cpp, SluaghEngine/Graphics/Renderer.cpp, SluaghEngine/Test/Asset/SimpleTexPS.txt, SluaghEngine/Test/EnemyMovementTest.cpp, SluaghEngine/Test/EnemyMovementTest.h, SluaghEngine/Test/FlowFieldTest.cpp, SluaghEngine/Test/Test.cpp, SluaghEngine/Test/Test.vcxproj, SluaghEngine/Test/Test.vcxproj.filters, SluaghEngine/includes/Gameplay/EnemyUnit.h, SluaghEngine/includes/Gameplay/Flowfield.h, SluaghEngine/includes/Gameplay/GameUnit.h, SluaghEngine/includes/Graphics/GraphicResourceHandler.h
Fixed the enemy movement test and changed the flowfield to work. Do check the flowfield, EnemyUnit, and GameUnit so these works as said earlier.
=> EnemyMovementTest

SluaghEngine/Gameplay/Flowfield.cpp, SluaghEngine/includes/Gameplay/Flowfield.h
Move along, nothing to see here.
=> Vector flow field

SluaghEngine/Core/MaterialManager.cpp, SluaghEngine/Core/RenderableManager.cpp, SluaghEngine/Graphics/GraphicResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/Test/BufferTest.cpp, SluaghEngine/Test/RenderableManagerTest.cpp, SluaghEngine/Test/ResouceHandlerTest.cpp, SluaghEngine/Test/Test.cpp, SluaghEngine/Test/rawLoaderEntries.txt, SluaghEngine/includes/Graphics/GraphicResourceHandler.h, SluaghEngine/includes/ResourceHandler/IResourceHandler.h, SluaghEngine/includes/ResourceHandler/ResourceHandler.h, SluaghEngine/includes/Utilz/Event.h
The resource handler can now load stuff with async.
Tests have been done and they seem to work.
None use the async funct yet.
QUICK and LAZY not implemented yet.
=> Implemented Async Resource Loading

SluaghEngine/Gameplay/EnemyUnit.cpp, SluaghEngine/Gameplay/Flowfield.cpp, SluaghEngine/Gameplay/GameUnit.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/Test/Config.ini, SluaghEngine/Test/RoomCreationTest.cpp, SluaghEngine/includes/Gameplay/EnemyUnit.h, SluaghEngine/includes/Gameplay/GameUnit.h, SluaghEngine/includes/Gameplay/Room.h
Rooms now have collision inside them. Note that the enemies are the ones fixing collision now. For themselves.
=> Fixed room collision

SluaghEngine/Audio/AudioSound.cpp, SluaghEngine/Audio/AudioStream.cpp, SluaghEngine/Core/AudioManager.cpp, SluaghEngine/Core/Engine.cpp, SluaghEngine/Test/AudioTest.cpp, SluaghEngine/Test/Config.ini, SluaghEngine/Test/rawLoaderEntries.txt, SluaghEngine/includes/Audio/AudioSound.h, SluaghEngine/includes/Audio/AudioStructType.h, SluaghEngine/includes/Core/AudioManager.h, SluaghEngine/includes/Core/Engine.h, SluaghEngine/includes/Window/IWindow.h, SluaghEngine/includes/Window/WindowSDL.cpp, SluaghEngine/includes/Window/WindowSDL.h
Decoupled optionHandlern from window and aound.
Fixed so It no longer should crash if no audio device can be found.
=> Fixed error

SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Test/GameStateTest.cpp, SluaghEngine/includes/Gameplay/PlayState.h, SluaghEngine/includes/Gameplay/PlayerUnit.h
Created the Playstate loop and the UpdateInput function
=> PlayState loop and UpdateInput()

SluaghEngine/Audio/AudioSound.cpp, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.h, SluaghEngine/SluaghEngine.sln, SluaghEngine/Test/ResourceHandlerTest.cpp, SluaghEngine/includes/ResourceHandler/IResourceHandler.h
You can now recursivly call loadresource.
And it is thread-safe
=> Load Resources in LoadResource

SluaghEngine/Core/MaterialManager.cpp, SluaghEngine/FBX_Converter/FBXConverter.cpp, SluaghEngine/FileParser/main.cpp, SluaghEngine/Gameplay/EnemyFactory.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Test/DebugRenderTest.cpp, SluaghEngine/Test/InstancingTest.cpp, SluaghEngine/Test/LightTest.cpp, SluaghEngine/Test/MaterialManagerTest.cpp, SluaghEngine/Test/PlayerMovementTest.cpp, SluaghEngine/Test/RecordingProjectileTest.cpp, SluaghEngine/Test/RenderableManagerTest.cpp, SluaghEngine/Test/SkeletonAnimationTest.cpp, SluaghEngine/Window/WindowSDL.cpp, SluaghEngine/includes/Core/MaterialManager.h, SluaghEngine/includes/FBX_Converter/Datatypes.h, SluaghEngine/includes/FBX_Converter/FBXConverter.h, SluaghEngine/includes/Graphics/FileHeaders.h
loads material and sets textures from them
=> Loads material

SluaghEngine/Gameplay/BehaviouralTreeFactory.cpp, SluaghEngine/Gameplay/FaceThePlayerLeaf.cpp, SluaghEngine/Gameplay/ForestTrainer.cpp, SluaghEngine/Gameplay/GlaistigAttackLeaf.cpp, SluaghEngine/Gameplay/LineOfSightCondition.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/ProjectileFactory.cpp, SluaghEngine/Gameplay/RandomSelector.cpp, SluaghEngine/Gameplay/RandomSequence.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/Test/SluaghTest.cpp, SluaghEngine/Test/Test.cpp, SluaghEngine/includes/Gameplay/DecisionTree.h, SluaghEngine/includes/Gameplay/RandomForest.h, SluaghEngine/includes/Gameplay/Room.h
Added a Slaugh test (our slaugh is fucking stupid!), fixed a memory leak and done some debugging in Gameplay-related classes.
=> SlaughTest

SluaghEngine/Core/GUIManager.cpp, SluaghEngine/Core/GUIManager.h, SluaghEngine/Graphics/DeviceManager.cpp, SluaghEngine/Graphics/PipelineHandler.cpp, SluaghEngine/Graphics/Renderer.cpp, SluaghEngine/Graphics/Renderer.h, SluaghEngine/Test/AudioTest.cpp, SluaghEngine/includes/Core/IGUIManager.h, SluaghEngine/includes/Graphics/GUIInfo.h, SluaghEngine/includes/Graphics/IRenderer.h
You can use -1 to use texture dimensions.
There is also both screen and GUI
=> You can now set absolute width/height for GUIs

SluaghEngine/Core/AnimationManager.cpp, SluaghEngine/Core/AnimationStructs.h, SluaghEngine/Core/AnimationSystem.cpp, SluaghEngine/FBX_Converter/FBXConverter.cpp, SluaghEngine/Test/SkeletonAnimationTest.cpp, SluaghEngine/includes/FBX_Converter/Datatypes.h, SluaghEngine/includes/FBX_Converter/FBXConverter.h
Added more exceptions in the FBX Converter
=> More exceptions in FBXConverter

SluaghEngine/Gameplay/Game.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/Projectile.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/ParseFiles.bat, SluaghEngine/includes/Gameplay/EventStructs.h, SluaghEngine/includes/Gameplay/KeyBindings.h, SluaghEngine/includes/Gameplay/Projectile.h, SluaghEngine/includes/Gameplay/Room.h
Fixed bug (issue 955) where healing had no default amount and killed the target if applied. Also fixed so that it is now easier to transition between rooms.
=> Fixed a bug and made room transition easier

SluaghEngine/Core/AnimationManager.cpp, SluaghEngine/Core/AnimationManager.h, SluaghEngine/Core/AnimationStructs.h, SluaghEngine/includes/Core/IAnimationManager.h
- Added animationflags for forcing and blocking blending
=> Animation Blending Flags. Issue #768.

SluaghEngine/Core/AnimationManager.cpp, SluaghEngine/Core/AnimationSystem.cpp, SluaghEngine/Core/MaterialManager.cpp, SluaghEngine/Core/RenderableManager.cpp, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.h, SluaghEngine/includes/ResourceHandler/IResourceHandler.h, SluaghEngine/includes/Utilz/Concurrent_Unordered_Map.h
It is now possible to start an animation that is not loaded, in that case the animation will be loaded. This is all done in sync.
=> Loading animations the first time they appear

SluaghEngine/Build/Asset/Shaders/Vertex/SkinnedCubeDepthVS.hlsl
Added a missing shader from the last PR.
=> Added shader.

SluaghEngine/Gameplay/CharacterCreationState.cpp, SluaghEngine/Gameplay/HUD_Functionality.cpp, SluaghEngine/includes/Gameplay/HUD_Functionality.h
=> Another Emergency fix

SluaghEngine/Gameplay/CharacterCreationState.cpp, SluaghEngine/Gameplay/FlowFieldMovementLeaf.cpp, SluaghEngine/Gameplay/LeapAtPlayerLeaf.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/ProjectileFactory.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/includes/Gameplay/GameUnit.h, SluaghEngine/includes/Gameplay/LeapAtPlayerLeaf.h, SluaghEngine/includes/Gameplay/PlayState.h, SluaghEngine/includes/Gameplay/ProjectileFactory.h
Issue 1071 and issue 1064.
* Glaistig now even more infuriating to do battle against.
* Bodach no longer leaves the map.
=> Glaistig damage when dead. Bodach goes on Adventure.

SluaghEngine/Core/AudioManager.cpp, SluaghEngine/Gameplay/PlayState.cpp
=> Fixed Stereo sound for enemy death sounds

SluaghEngine/Gameplay/Items.cpp
Fixed crossbow local rotation for attack animation
=> Crossbow local rotation fix

SluaghEngine/FBX_Converter/FBXConverter.cpp
Changed ConvertToLeftHanded function FBXConverter and corrected the rotation calculation
=> Convert animations from RH to LH. Issue #714.

SluaghEngine/Gameplay/HUD_Parsing.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/includes/Gameplay/HUD_Parsing.h, SluaghEngine/includes/Gameplay/PlayState.h
Added enemy healht bars and health bar backgrounds and some code to properly import them
=> Added enemy health bars as GUIbuttons and code to find them

SluaghEngine/Audio/AudioSound.h, SluaghEngine/Audio/AudioStream.cpp, SluaghEngine/Audio/AudioStructType.h
=> Mono sound to Stereo

SluaghEngine/Gameplay/Items.cpp
=> Missing mat now on items

SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/includes/Gameplay/Room.h
Fireplaces spawn only on 1x2 tiles near walls. Paintings have a 2% chance of spawning per wall. (about 1-3 paintings per room)
=> Fireplace and paintings

SluaghEngine/Gameplay/CharacterCreationState.cpp, SluaghEngine/Gameplay/MainMenuState.cpp
=> Removed two runtime memory leaks from MainMenuState and CharacterCreationState

SluaghEngine/Core/ImGuiConsole.cpp, SluaghEngine/Core/ImGuiConsole.h, SluaghEngine/Core/LightManager.cpp, SluaghEngine/DevConsole/CMDConsole.cpp, SluaghEngine/DevConsole/Commands.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/includes/DevConsole/CMDConsole.h, SluaghEngine/includes/DevConsole/Commands.h, SluaghEngine/includes/DevConsole/IConsole.h, SluaghEngine/includes/Gameplay/PlayerUnit.h
Issue # 1176
* The issue was caused by an error in LightManager::Destroy
* Added a speedcheat. setspeed <value> in console
* Commands can now be removed from the console as well. (Good for when the object that added the command is destroyed, making the command invalid)
* Fixed a bug in Room.cpp
* Fixed several bugs in LightManager
=> Fixed lights turning on/off weirdly + other things.

SluaghEngine/Gameplay/MainMenuState.cpp
Readded the tutorial start button
=> Bundle of joy

SluaghEngine/Build/Asset/Shaders/Geometry/ParticleGSUpdate.hlsl, SluaghEngine/Core/ParticleSystemManager.cpp, SluaghEngine/Core/ParticleSystemManager.h
Issue #1183
Fixed glaistig particles. It now moves to the target(player) and then drains back to the glaistig.
=> Glaistig Particle behvaiour

SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.h, SluaghEngine/includes/ResourceHandler/IResourceHandler.h
Not connected to any issue
Additions:
* Exist function in resource handler
* GetMemoryUsage in resource handler
Changes: 
* Now writes the actual memory usage that the resource handler use.
=> Room streaming timer

SluaghEngine/Gameplay/Room.cpp
Not connected to any existing issue.
* Added a painting of St. Perlaugh Stromlain, an important figure in Scottish history.
=> Added another painting

SluaghEngine/Gameplay/Room.cpp
-- Everything marked like this must be removed -- 
Connected to issue #1269
Changes: 
Fixed wall if statments
Wall not right next to bushes. issue #1269
Room 20 having dead space instead of wall. issue #1269
=> Fixed wall problems

SluaghEngine/Core/Engine.cpp, SluaghEngine/Game/StreamTimings.csv, SluaghEngine/ResourceHandler/ResourceHandler.cpp, SluaghEngine/ResourceHandler/ResourceHandler.h, SluaghEngine/includes/ResourceHandler/IResourceHandler.h
Connected to issue #1268 
Additions:
Added new evict policies for resource handler
* FIFO ( First in first out)
* LIFO ( Last in first out)
* RANDOM
* LUFO ( Least used first out)
* MUFO ( Most used first out)
Changes: 
* Max VRAM limit is now default to 256mb
=> Evict policies

SluaghEngine/Gameplay/CharacterCreationState.cpp
=> Fixed speed hack

SluaghEngine/Gameplay/Room.cpp, SluaghEngine/Gameplay/Weapon.cpp, SluaghEngine/includes/Gameplay/Room.h
Additions:
* Added new prop sets
-- 2 fireplaces with props
-- Table with props
-- Potatobag set
-- Floortorch set
Changes:
* Changed the depth of item icons to fix z-fighting with the "taking damage" indicator
=> More props

SluaghEngine/Gameplay/Game.cpp
* Added pause text at the top
* New continue button
* Adjusted position of buttons
=> Updated pause menu

SluaghEngine/Gameplay/PerkFactory.cpp, SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp
Sluagh perks.
Connected to issue
Old removed sluagh epic (my bad)
Additions: 
*The sluagh will now save and read player perks.
Changes: 
*Save player and read player has had perks added.
#1369, don't check win con if player's health is <= 0.0f
Warnings:
REMOVE YOUR SLUAGH FILE!
=> Perks for Sluagh

SluaghEngine/Gameplay/SluaghRoom.cpp, SluaghEngine/includes/Gameplay/Room.h, SluaghEngine/includes/Gameplay/SluaghRoom.h
Connected to issue #nr1373 & #1343
Additions:
Added a health bar for the slaugh
Changes:
Made the UpdateHPBar function virtual in room, and it is now called in the update funciton of the slaughroom
=> hp bar on slaugh

SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/Room.cpp
Connected to none
Changes: 
* Level does no longer progress when exiting to main menu.
=> Level prog fix

SluaghEngine/Gameplay/SluaghRoom.cpp
Connected to issue #1377
Additions: 
Nothing new added
Changes:
Removed the toggle gui element lines in the sluaghroom constructor to stop the sluagh hpbar from appearing 
Bugs Resolved:
#1377 Se changes above
=> Sluagh hpbar bugfix

SluaghEngine/Core/Engine.cpp, SluaghEngine/ImGuiDX11SDL/ImGuiDX11SDL.cpp, SluaghEngine/Window/WindowSDL.cpp, SluaghEngine/Window/WindowSDL.h, SluaghEngine/includes/Window/IWindow.h
Connected to issue #1403
Additions
* Added frame time and memory usage to title of window to make it easier for Francisco and c/o to see it when they test our program.
Changes
* Fixed ImGui not working correctly in fullscreen.
* Made it easier to see the numbers for memory usage in the plot_memory_usage tab of the devconsole.
=> Final fixes

SluaghEngine/Gameplay/CharacterCreationState.cpp, SluaghEngine/Gameplay/HUD_Functionality.cpp
Connected to issue #nr
None, standalone fix
Additions: 
New skill buttons, text that says chose your skill/perk
Changes: fixed delete specific button func.
=> Chose  your skill/perk

SluaghEngine/Gameplay/TutorialState.cpp
-- Everything marked like this must be removed -- 
Connected to issue #1407
Additions: -- New Things --
New sounds for pech
Changes: 
Old sounds for pech
=> Pech sounds

SluaghEngine/Gameplay/Room.cpp, SluaghEngine/Test/ParseFiles.bat
Connected to issue #1313
-Resulved bug 1313 normalmaps wall
-Fixed grass texture
=> Normalmap bugs

SluaghEngine/Gameplay/Room.cpp
-- Everything marked like this must be removed -- 
Connected to issue #1370 
Changes:
* Now also takes the torch tiles into account when doing the collision check
=> Fixed collision triggering against torches

SluaghEngine/Gameplay/ProjectileFactory.cpp
Connected to issue #1401
Additions:
Nothing
Changes:
Changed the SetToMousePos behaviour so it checks if it is the player or not who is the owner, and if it is not the player then the desired position is the player position.
=> Sluagh target bug

SluaghEngine/Gameplay/PlayState.cpp, SluaghEngine/Gameplay/PlayerUnit.cpp, SluaghEngine/Gameplay/Room.cpp, SluaghEngine/Gameplay/Sluagh.cpp, SluaghEngine/includes/Gameplay/PlayerUnit.h
Bugs Resolved: -- If none remove --
*The sluagh will not crash when loaded in after the game has been restarted
*The sluag's skills will not have a cooldown of 0 at start of the room
*The nuckelavee will now work properly.
*The pech should not spawn in the walls anymore.
*The health bars are no longer displayed once the death animation of an enemy starts.
New Bugs: 
The sluagh might vibrate into hyperspace. Sorry.
=> A lot of small bugfixes

SluaghEngine/Core/Engine.cpp, SluaghEngine/Core/ParticleSystemManager.cpp, SluaghEngine/includes/Core/IParticleSystemManager.h
-- Everything marked like this must be removed -- 
Connected to issue #nr
Changes: 
fixed so partsys use delta time from window
=> part delta
