dastyk/SE

- SluaghEngine/Graphics/include/IRenderer.h
Contains MeshGUID, textureGUIDArray and textureGUIDCount. Textures will be unused for now but follows the format we will use later on.
> Defined RenderObjectInfo for first sprint.

- SluaghEngine/Core/CameraManager.cpp
- SluaghEngine/Core/CollisionManager.cpp
- SluaghEngine/Core/DebugRenderManager.cpp
- SluaghEngine/Test/ConsoleTest.cpp
- SluaghEngine/Window/WindowSDL.cpp
- SluaghEngine/Window/WindowSDL.h
- SluaghEngine/includes/Core/CameraManager.h
- SluaghEngine/includes/Core/CollisionManager.h
- SluaghEngine/includes/Window/IWindow.h
How to print it to the console is visible in ConsoleTest.cpp. There's not really any reason to hardcode "Check if pick picks anything every time the user clicks" into the engine.
> Added ability to check which entity a pick collides with in collision manager.

- SluaghEngine/FBX_Converter/FBXConverter.cpp
- SluaghEngine/Graphics/AnimationSystem.cpp
A temporary fix to correctly display animations by scaling the final transformation matrix with a scaling in  the negative x-axis
> Temporary fix for inverting animations

- SluaghEngine/FBX_Converter/FBXConverter.cpp
- SluaghEngine/includes/FBX_Converter/Datatypes.h
- SluaghEngine/includes/FBX_Converter/FBXConverter.h
Added a string to the texture datatype in FBXConverter to specify which channel the texture is currently bound to. "DiffuseColor" or "NormalMap".
> Added texture channel in material file

- SluaghEngine/Core/MaterialManager.cpp
- SluaghEngine/Core/RenderableManager.cpp
The CreateRenderableObject function in renderable manager and Create in material manager will now change the mesh/shader/material,etc. when the entity is already registered.
> Meshes and material can now be changed for an entity

- SluaghEngine/Core/Core.vcxproj
- SluaghEngine/Core/Core.vcxproj.filters
- SluaghEngine/Core/DataManager.cpp
- SluaghEngine/Core/DataManager.h
- SluaghEngine/Core/DecalManager.cpp
- SluaghEngine/Core/Engine.cpp
- SluaghEngine/Core/Engine.h
- SluaghEngine/Core/EventManager.cpp
- SluaghEngine/Core/EventManager.h
- SluaghEngine/Core/IDataManager.cpp
- SluaghEngine/Core/IEventManager.cpp
- SluaghEngine/Gameplay/Room.cpp
- SluaghEngine/Particle_Editor/Particle_Editor.vcxproj
- SluaghEngine/includes/Core/IDataManager.h
- SluaghEngine/includes/Core/IEngine.h
- SluaghEngine/includes/Core/IEventManager.h
* Weapons(a pink cube) now has a 50% chance to spawn when killing an enemy.
* Blood is now splattered below an enemy when they die.
-- Blood splatter will be in the same location in every room...
* Event manager now support lifetimes for entities.
* Event manager now supports registering userdefined events to entities. This can/will be used for the weapon pickup system
- Added the DataManager. Including
-- The ability to register bool, int, float and string to an entity
-- Multiple variables for one entity.
-- WARNING!! Strings must have the suffic s, "asd"s
* This PR will resolve Bug #970
When I implemented this the Glasting did not have its model or animations. Probably because I didn't have the latest assets.
I have not changed any assets, but added a blood splatter texture. I will …
> Weapon pickup spawn

- SluaghEngine/Core/AnimationManager.cpp
- SluaghEngine/Core/RenderableManager.cpp
- SluaghEngine/Core/RenderableManagerInstancing.cpp
- SluaghEngine/Core/TransformManager.cpp
- SluaghEngine/Gameplay/Room.cpp
Issue 969.
* Fixed crash when entity is attached to joint is destroyed and animation tries to update it.
* The transform manager now looks through more entities proportional to how many entities are registererd when performing the garbage collection. There was not really a noticable difference.
* The issue with stuff hanging around after being destroyed seems to be gone
* Re-enabled the threading in transformmanager matrix calculations.
*Small optimisations in the transform manager, Cut the frame time for the transformmanager in half. (Down from around 1 ms per frame to 0.5ms during "usual" gameplay.)
*Adaptive GC for the renderable manager, made no noticable difference.
*Small optimisation in RenderableManagerInstancing::UpdateTransform, skipping an extra copy of a matrix
> Adaptive GC, bugfixes, optimisations

- SluaghEngine/Core/AnimationManager.cpp
- SluaghEngine/Core/RenderableManager.cpp
Issue 1081.
The crash was caused by the animation manager manually destroying objectrs in the renderablemananger.
> Fixed crash when animated object is destroyed.

- SluaghEngine/Core/CollisionManager.cpp
- SluaghEngine/Core/ParticleSystemManager.cpp
- SluaghEngine/Gameplay/Items.cpp
- SluaghEngine/Gameplay/PlayState.cpp
- SluaghEngine/Gameplay/Room.cpp
- SluaghEngine/includes/Gameplay/Room.h
Items are now destroyed when the player transitions to another room.
It solves issue #1005
> Items are no longer static between rooms

- SluaghEngine/Graphics/Renderer.h
Issue 1094.
There were only 4 bits in the jobID representing the render group, but there were a total of 18 groups available...
It has been fixed by letting 5 bits represent the group.
> Fixed a bug in the renderer.

- SluaghEngine/Core/DecalManager.cpp
Issue #1128
The render job was not updated when a decal was removed.
> Fixed decal crash #1128

- SluaghEngine/Core/GUIManager.cpp
The game now uses 30MB less VRAM when the game part is running.
> Release texture from GUI manager.

- SluaghEngine/Gameplay/PlayerUnit.cpp
- SluaghEngine/includes/Gameplay/PlayerUnit.h
Attempting to switch weapon in the middle of an attack animation is no longer allowed and won't freeze the player animations. Weapons can only be switched if the player is not attacking, which is determined by the attack cooldown.
> Attack Animation Freeze Fix. Issue #1167

- SluaghEngine/Build/Asset/Shaders/Pixel/SimplePS.hlsl
- SluaghEngine/Build/Asset/Shaders/Pixel/SimpleTexPS.hlsl
- SluaghEngine/Gameplay/EnemyFactory.cpp
- SluaghEngine/Gameplay/TutorialState.cpp
- Issue #1181 was caused due to only using animations for the lower body
- Issue #1182 was caused due to loading an old attack animation
- Issue #1089 only required adjustments in the Move function for the Nuckelavee in EnemyFactory
> Tutorial and Nuckelavee Fixes

- SluaghEngine/Gameplay/Room.cpp
Gathered width and height for window with optionshandler instead by using the function GetOptionUnsignedInt. This seems to have solved the problem.
> Floating healthbars in fullscreen fix. Issue #1227

- SluaghEngine/Gameplay/Room.cpp
- SluaghEngine/includes/Gameplay/Room.h
Connected to issue #1222
Additions:
* Added support for windows, mesh and mat
* Windows to the left (west) will always be closed as per the mythology
Changes: 
* Added new function (CreateWindows) to room.cpp
Texture needs to be added. UV also needs adjusting. This will be done separately.
> Windows in rooms #1222

- SluaghEngine/Build/Asset/Shaders/Pixel/SimpleLightTransparentPS.hlsl
- SluaghEngine/Core/AnimationManager.cpp
- SluaghEngine/Core/AnimationManager.h
- SluaghEngine/Core/CameraManager.cpp
- SluaghEngine/Core/EntityManager.cpp
- SluaghEngine/Core/EntityManager.h
- SluaghEngine/Core/ImGuiConsole.cpp
- SluaghEngine/Gameplay/Game.cpp
- SluaghEngine/Gameplay/Gameplay.vcxproj
- SluaghEngine/Gameplay/Gameplay.vcxproj.filters
- SluaghEngine/Gameplay/PlayState.cpp
- SluaghEngine/Gameplay/PlayerUnit.cpp
- SluaghEngine/Gameplay/TutorialState.cpp
- SluaghEngine/Gameplay/WinState.cpp
- SluaghEngine/includes/Core/IAnimationManager.h
- SluaghEngine/includes/Core/IEntityManager.h
- SluaghEngine/includes/Gameplay/IGameState.h
- SluaghEngine/includes/Gameplay/PlayerUnit.h
- SluaghEngine/includes/Gameplay/SluaghRoom.h
- SluaghEngine/includes/Gameplay/WinState.h
Connected to issue #1204
Additions:
* Added win screen for when the sluagh is killed.
* The win screen is also used on player death as a placeholder.
* Added a command to kill the player in the console
* All entities are destroyed between state changes
* Added a new shader that is only used for the winscreen. 
Changes: 
* default camera is no longer used since all entities are destroyed when the state changes.
> Issue 1204 win state

- SluaghEngine/Core/DataManager.cpp
- SluaghEngine/Core/EventManager.cpp
- SluaghEngine/Core/MaterialManager.cpp
- SluaghEngine/Gameplay/Consumable.cpp
- SluaghEngine/Gameplay/Gameplay.vcxproj
- SluaghEngine/Gameplay/Gameplay.vcxproj.filters
- SluaghEngine/Gameplay/Items.cpp
- SluaghEngine/Gameplay/PlayState.cpp
- SluaghEngine/Gameplay/PlayerUnit.cpp
- SluaghEngine/Gameplay/Room.cpp
- SluaghEngine/Gameplay/Sluagh.cpp
- SluaghEngine/Gameplay/TutorialState.cpp
- SluaghEngine/Gameplay/Weapon.cpp
- SluaghEngine/ResourceHandler/ResourceHandler.cpp
- SluaghEngine/includes/Gameplay/Consumable.h
- SluaghEngine/includes/Gameplay/EventStructs.h
- SluaghEngine/includes/Gameplay/Items.h
- SluaghEngine/includes/Gameplay/PlayerUnit.h
- SluaghEngine/includes/Gameplay/Stats.h
- SluaghEngine/includes/Gameplay/Weapon.h
- SluaghEngine/includes/ResourceHandler/IResourceHandler.h
Connected to issue #1220 
Additions:
* kill command, kills all enemies in the current room
* give command, give the player an item
* drop command, drop an item on the player
* Added a sword to the Sluagh in the tutorial.
* Added max stats to str, agi, whi, damage and health (Used for random cap)
-- Random stats can now be generated with ex. Stats::GetRandStr()
Changes: 
* Indications of whether or not an item on the ground is better has changed.
--  Numbers are no longer displayed
-- Info for currently equipped weapon can not be showed individually.
-- Green text indicated that the item on the ground has a higher stat than current.
-- Yellow indicates the same stats.
-- Red indicates worse.
* Item header refactor
-- Weapons moved to seperate header.
-- Consumables moved to seperate …
> Issue 1220 item vis

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- SluaghEngine/Core/DecalManager.cpp
- SluaghEngine/Core/DecalManager.h
- SluaghEngine/Gameplay/PlayState.cpp
- SluaghEngine/Gameplay/Room.cpp
- SluaghEngine/includes/Core/IDecalManager.h
- SluaghEngine/includes/Gameplay/PlayState.h
Connected to issue #1242
Changes: 
Decals had to be able to be created without being visible at start. When this was fixed, a decal was placed on a painting.
New Bugs:
After the player has died and returns to the menu, the buttons in the character creation state are flashing
Notes:
Paintings can now have decals
> Decal placement

- SluaghEngine/Gameplay/Weapon.cpp
Connected to issue  #1257
Additions:
* Weapons now have random projectiles.
* 3 for wand
* 3 for crossbow
* 1 for sword
> Weapon diversity

- SluaghEngine/Gameplay/Game.cpp
- SluaghEngine/includes/Gameplay/Game.h
Connected to issue #1289 
Additions:
*Pause menu with working buttons to keep playing or exit the game
Changes:
* Escape key will bring up the pause menu in game. In the main menu it will exit as normal
New Bugs:
* The hover texture only works the first time the menu is opened. If we open it again and hover over a button, nothing happens. We can still click it like normal.
-- Connected to issue #1290
Notes:
* Better textures need to be made to indicate function of the buttons
> Pause menu

- SluaghEngine/Gameplay/PlayState.cpp
Connected to issue #1364
Changes: 
Made sure already visited adjacent rooms were not overwritten
> Minimap Adjacent Room Display Fix. Issue #1364

- SluaghEngine/Build/Asset/Shaders/Pixel/DecalPS.hlsl
Connected to issue #1372 
#1372  hlsl packing rules fucking things up. Doesn't crash from solexplosion any longer when the number of decals increases.
Notes
Fucking hlsl packing rules.
> Decal tweak

- SluaghEngine/Game/Main.cpp
- SluaghEngine/Gameplay/CharacterCreationState.cpp
- SluaghEngine/Gameplay/Game.cpp
- SluaghEngine/Gameplay/Gameplay.vcxproj.filters
- SluaghEngine/Gameplay/HUD_Functionality.cpp
- SluaghEngine/Gameplay/HUD_Parsing.cpp
- SluaghEngine/Gameplay/ProjectileFactory.cpp
- SluaghEngine/includes/Gameplay/CharacterCreationState.h
- SluaghEngine/includes/Gameplay/HUD_Functionality.h
- SluaghEngine/includes/Gameplay/HUD_Parsing.h
Connected to issue #nr
#1376
Additions:
New skill HUD files (placeholders)
Changes:
Å Ä Ö now works in skill description, new hud files so all skills should be visible again.
#1376
Notes :
HUD files are placeholders until all skill pictures have been drawn.
> Bug NR #1376

- SluaghEngine/Gameplay/Game.cpp
Connected to issue #1384 
Changes:
* Now removes the playstate thats in tempState when switching from pause menu to main menu
> Fixed memory leak when chaning state

- SluaghEngine/Gameplay/HUD_Functionality.cpp
Connected to issue #nr
None, standalone fix
Additions: 
Last skill button
#1409
can now rezise window and button text follows accordingly
> Fixed button text error and added last skill button
